language: node_js
node_js: 8

before_script:
  - npm install firebase-tools -g

script:
  - echo 'deploying!'

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash deploy.sh
    on:
      branch: master
