language: node_js
node_js:
- '8'
deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  message: build $TRAVIS_BUILD_NUMBER $TRAVIS_BRANCH/$COMMIT_HASH
env:
  global:
    secure: eTGkgO53hYQCeJYH1G05528qwVtwUhvTcxsFeWb7YMazuwq/MF2gF31WZHhIe9OYpUedasC6fUeNqb99Rf2ZXVRsjyCCne6WHcC2NB7NTSfumOp3sx7EmFjyJY+yaB76c3ffvz9Qt9yuYT3IHMubUgxCN/QUCT28T+JtdQZMX8pKKslxZowkfzknjz/IeeujgFlEB5UDCRPncOyCH0AuGp+hrq5DmIfenI5rDo+QEgj+D5cQF+9QQrHBFDgySt4gvN6kD0y4vx8eRxAlVq8F7ZXwp2rmIjNrgt3obuYVn65W50Nwmj8mP1grFN7mX1aUlHarQGQuhZbPHB27TZtuLoUQbUDxEoPIq7yAla62DaWYZBr4BrLB5u9zY+34pgOa92jmK6Q28rW/of+g4ZP2p7ZaaLN/TaQHyVoihSe7f7WKU+l64bzFjW8tDQt1RNofHlYmQzH3ngb8momMj20m7tpd5fsbXxyh9t4n/0y9rDXlxki4xN0eTMcT/RS1hma7cApj7wt+lfPTa/f8cZqvoUIL/seHMtpSWTH982CSMXVeKP4d0D3DR71CofqP2dEc28G6getQS9ii1pyGruX4Bi/jzWGXh33AkLtm4EF9iGxF+5p6PeXFcM4ahyio9G+Q4dLLNSeu1ZuqumVZ5PWExhgmA3hp8qwA2yUZjeYy3rQ=
