language: node_js
node_js:
- '8'
deploy:
  provider: firebase
  token:
    secure: Xiy3Zz2QfliqKAlln30hSXu1qfZgWS4BG10v5C81S/EVXOWvMiFTHuvq9P6lxmckUd6e9/I3wLISTKN/At8LocdvLwcMf+Tbd+Q2PH5HKfdm9T0lwy7jLSkBxCxSLLDrHYtadwD1b9M428tCa3NA3hW0Z+t2qVACRXGTzzwzAMBcJTtUYdz0AhZaboyh0O51LSuawQ8aO4tW2Ip4wo7OMQpjxvsqOU+7S4xILXXoUztG4yJH82NPIXjdK8OVOjMGT7p3KuGD0DFQRaffoS4+oGc8NFF9nWbj5UhU2J1KG8OYp72inT1Agd1rY14AFXNYiRxQCZHf+0rWs2//pWLpUy84lGftqMGBGPNL5XdUOwys0JLgvp03B1b8BLxaTJv0ty0yGA2spDgvllgWg332X+S60VEs6445GvL2kGbVs8+rV+50LlfLA3NxtKotnCpMYhKyObeMuELa3K6mXn+xJ222EoiEia422rfoztr8rbeVlyAhNp1cNNMiEj77OFCPud8mXdTZt/fII1TM1vx+iB+0hnjIruefdGreoh/u2SfaT9jC+T3W21+jlnFOOj9iU0W430FcZOAn8KB7Poojo/nSuepD/LAt4j24b4VmcNV4gLP3X2ZDI4TYUmhxb/gCfzuLZu9v+nLQXrtOiBUEi1x5Fqan5apWJoLnewMNQao=
  message: build $TRAVIS_BUILD_NUMBER $TRAVIS_BRANCH/$COMMIT_HASH
