language: node_js
node_js:
- '8'
deploy:
  provider: firebase
  token:
    secure: "BnzKtrzBaI/uLHoezYpBVqQ/VwhIyil+EketIS3qYwv4ga9qn2OREVTCOUFhIKznTPEs5XCzPhqLElT7CcxK3ly2PxEnjnPEDks92LVv91/rDo6+Ovz/LfmXhnRGGpABdWaGeKvDpJK2h1uribefYOi8bKy4sySIYeAa5ZQnZnWXbkCLDz17A6hjGFaheZAxL38x4g1/uFJnd12yysmNjModM6UwT1GCSorL4hX83WgrAfE1jRQAiNrojDxfpmY/1kqosrrRa1Sb+lQ00V83YmHWJfotdFII6lO07w8xqApZ8WWflNTmcSs7mWNjFHAjz726LNhP9xuf+OYGPqS6U2Dlk4B2BfZaaQTkQF+01jwnuQuOJCoiKBKBhBtrYjjSLsCa9PW7yN0iH3xiT08p4/KWdB8mZzwUr0ZpFpeayBFo/SGk/Mj0ltvo+t+tZQk2+rg/eyrE9glMWOS07zIh65AGI9LRSziRPK5SDPZ+8J4aAL6FviJbrScgOYOR2HITuhZCaEYlCbeKxvmaqbRNHn/nlXzNWgortBQfz/aOekvmH5ypvV6jxd4QkZdL1MrCspctiosODnXLBhUdWuKjotZsRbz5pRdTskFveB/ZNdWXfCHT1A6K1bpm3Don34SEsK8POLp3Cv3XPQ3uthCwcL0Ey4j+g4SrFn0jAuBNrTI="
  message: build $TRAVIS_BUILD_NUMBER $TRAVIS_BRANCH/$COMMIT_HASH
