language: node_js
node_js:
  - "6"
  - "iojs"
before_install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy -m "build $TRAVIS_BUILD_NUMBER $TRAVIS_BRANCH/$COMMIT_HASH" --non-interactive --token $FIREBASE_TOKEN
